// i18n/en-US.js
export default {
  // ---- Ações genéricas ----
  'btn.salvar': 'Save',
  'btn.cancelar': 'Cancel',
  'btn.confirmar': 'Confirm',
  'btn.tentar_novamente': 'Try again',

  // ---- settingsApi.js ----
  'erro.salvar_configuracoes_generico': 'Could not save settings. Please try again.',
  'erro.sem_conexao': 'No connection to the server. Check your internet and try again.',

  // ---- settingsPaineis.js ----
  'sucesso.configuracoes_salvas': 'Settings saved successfully.',

  // ---- settingsArquivos.js ----
  'erro.abrir_documento': 'Could not open the document. Check if pop-ups are blocked.',

  // ---- settingsSenha.js ----
  'senha.erro.nao_coincidem': 'Passwords do not match.',
  'senha.erro.confirmacao_expirada': 'Your identity confirmation expired. Close and try again.',
  'senha.erro.alterar_generico': 'Could not change the password. Please try again.',
  'senha.sucesso.alterada': 'Password changed successfully.',

  // ---- settingsTotp.js ----
  'totp.qrcode.falha_carregar': 'Could not load the QR code right now -- use the code below to set up manually, or reload the page and try again.',
  'totp.secret.prefixo': 'Or enter manually:',

  // ---- settingsModal.html — estrutura e aba User ----
  'settings.title': 'Settings',
  'settings.tab.user': 'User',
  'settings.tab.seguranca': 'Security',
  'settings.tab.preferencias': 'Preferences',
  'settings.tab.arquivos': 'Files',
  'settings.user.titulo': 'Basic information',
  'settings.user.subtitulo': 'Some data is managed by your institution and cannot be edited here.',
  'settings.user.alterar_foto': 'Change photo',
  'settings.user.foto_hint': 'JPG or PNG, up to 4MB.',
  'settings.user.nome': 'Name',
  'settings.user.telefone': 'Phone',
  'settings.user.email': 'Email',
  'settings.gerenciado_instituicao': 'Managed by your institution',

  // ---- settingsModal.html — aba Segurança ----
  'settings.seguranca.2fa_titulo': 'Two-step authentication',
  'settings.seguranca.2fa_descricao': 'Passkey (WebAuthn) and authenticator app (TOTP) — register at least one of these to enable two-step confirmation.',
  'settings.seguranca.adicionar_dispositivo': '+ Add new device',
  'settings.seguranca.totp_titulo': 'Authenticator app (TOTP)',
  'settings.seguranca.totp_descricao': 'Google Authenticator, Microsoft Authenticator or similar — it doesn\'t depend on Bluetooth or a USB port, only on the phone you already carry.',
  'settings.seguranca.totp_configurar': '+ Set up authenticator app',
  'settings.seguranca.totp_remover': 'Remove',
  'settings.seguranca.senha_titulo': 'Password',
  'settings.seguranca.senha_descricao': 'Used as the first factor, together with your institutional login.',
  'settings.seguranca.login_titulo': 'Login',
  'settings.seguranca.login_usuario': 'Login username',

  // ---- settingsModal.html — aba Preferências ----
  'settings.pref.tema_titulo': 'Theme',
  'settings.pref.tema_descricao': 'Choose the application\'s color scheme.',
  'settings.pref.acessibilidade_titulo': 'Accessibility',
  'settings.pref.fonte_label': 'Font size',
  'settings.pref.fonte_pequena': 'Small',
  'settings.pref.fonte_padrao': 'Default',
  'settings.pref.fonte_grande': 'Large',
  'settings.pref.idioma_titulo': 'Language',
  'settings.pref.idioma_label': 'Interface language',

  // ---- settingsModal.html — aba Arquivos ----
  'settings.arquivos.titulo': 'Documents',
  'settings.arquivos.descricao': 'Terms, policies and other institutional documents.',
  'settings.arquivos.termo_consentimento': 'Consent Terms',
  'settings.arquivos.termo_uso': 'Terms of Use',
  'settings.arquivos.visualizar': 'View',
  'settings.arquivos.baixar': 'Download',

  // ---- settingsModal.html — barra de salvar ----
  'settings.savebar.texto': 'You have unsaved changes',
  'settings.savebar.salvar': 'Save changes',

  // ---- settingsModal.html — modal TOTP ----
  'totp.nome': 'Authenticator app',
  'totp.modal.subtitulo': 'Scan the QR code in your authenticator app (Google Authenticator, Microsoft Authenticator or similar), or enter the code below manually.',
  'totp.modal.carregando': 'Generating setup code...',
  'totp.modal.codigo_label': 'Code generated by the app',

  // ---- settingsModal.html — modal Alterar senha ----
  'senha.alterar': 'Change password',
  'senha.modal.subtitulo': 'You will need to confirm your identity before setting the new password.',
  'senha.nova': 'New password',
  'senha.nova_hint': 'Minimum of 12 characters.',
  'senha.confirmar_nova': 'Confirm new password',

  // ---- stepupModal.html ----
  'stepup.titulo': 'Confirm your identity',
  'stepup.subtitulo_antes': 'To continue with',
  'stepup.subtitulo_depois': ', confirm again who you are.',
  'stepup.carregando': 'Checking available method...',
  'stepup.webauthn.hint': 'Use your security key, PIN or device biometrics when prompted by the browser.',
  'stepup.totp.hint': 'We could not confirm with your security key. Enter the code from your authenticator app.',
  'stepup.totp.codigo_label': 'Authenticator code',
  'stepup.senha.label': 'Current password',
  'stepup.senha.hint': 'After confirming your password, you will sign in with your Google account in a new window to complete the confirmation.',
  'stepup.senha.confirmar': 'Confirm password',
};